pipeline {
    agent any
    environment {
        ECR_REPOSITORY= credentials("ECR_REPOSITORY")
        AWS_ACCOUNT_ID= credentials("AWS_ACCOUNT_ID")
        AWS_ACCESS_KEY_ID= credentials("AWS_ACCESS_KEY_ID")
        AWS_SECRET_ACCESS_KEY= credentials("AWS_SECRET_ACCESS_KEY")
    }

    stages {
        stage("Continuous Integration") {
            steps {
                script {
                    echo "Linting repository"
                    sh "python tests/test_model.py"
                }
            }
        }

        stage("Login to ECR"){
            steps {
                script {
                    sh 'aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.eu-north-1.amazonaws.com'
                }
            }
        }

        stage("Build Image"){
            steps{
                script {
                    sh 'docker build -t ${ECR_REPOSITORY}:latest'
                }
            }
        }
    }

}