pipeline {
    agent any
    environment {
        ECR_REPOSITORY= credentials("ECR_REPOSITORY")
        AWS_ACCOUNT_ID= credentials("AWS_ACCOUNT_ID")
        AWS_ACCESS_KEY_ID= credentials("AWS_ACCESS_KEY_ID")
        AWS_SECRET_ACCESS_KEY= credentials("AWS_SECRET_ACCESS_KEY")
    }

    stages {
        stage("Continuous Integration") {
            steps {
                script {
                    echo "Linting repository"
                    sh "python tests/test_model.py"
                }
            }
        }
    }
}