pipeline {
  agent any
  environment {
    ECR_REPOSITORY = credentials('ECR_REPOSITORY')
    AWS_ACCOUNT_ID = credentials('AWS_ACCOUNT_ID')
    AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
  }

  stages {
    stage("Continuous Integration"){
        steps {
            script {
                echo "Linting repository"
                sh "python tests/test_model.py"
            }
        }
    }
    stage("Login to ECR"){
        steps {
            script {
                sh "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com"
            }
        }
    }
    stage("Build Image"){
        steps {
            script {
                sh "docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPOSITORY}:latest ."
            }
        }
    }
    stage("Push Image to ECR"){
        steps {
            script {
                sh "docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPOSITORY}:latest"
            }
        }
    }
    stage("Continuous Deployment"){
        steps {
            sshagent(['ssh_key']) {
                sh """
                    ssh -o StrictHostKeyChecking=no -l ubuntu 54.80.194.59 '
                        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com &&
                        docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPOSITORY}:latest &&
                        docker stop app || true &&
                        docker rm app || true &&
                        docker run -d --name app -p 80:8080 ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPOSITORY}:latest
                    '
                """
            }
        }
    }
  }

  post {
    always {
      sh 'docker system prune -f'
    }
  }
}